baseURL = "https://lyytrang.github.io/"
languageCode = "en-us"
title = "Lý Trang"
theme = "hugo-digital-garden-theme"
copyright = "Lý Trang ©"


[params]
  name = "Lý Trang"
  description = "Small bunny-musician."
  initials = "Lý Trang"
  googleAnalytics = ""

  [[params.social]]
    name = "YouTube" 
    link = "https://www.youtube.com/channel/UC5DZPuSIH_vxbBpOtXRSfXQ"
    icon = "fab fa-youtube"

  [[params.social]]
    name = "Instagram"
    link = "https://instagram.com/ly__trang"
    icon = "fab fa-instagram"

  [[params.social]]
    name = "Facebook"
    link = "https://www.facebook.com/profile.php?id=100080262098932&mibextid=ZbWKwL"
    icon = "fab fa-facebook"

  [[params.social]]
    name = "Bandcamp"
    link = "https://lytrang.bandcamp.com/music"
    icon = "fab fa-bandcamp"

  [[params.social]]
    name = "Email"
    link = "mailto:trang.lyha@gmail.com"
    icon = "fas fa-envelope-square"

[menu]
  [[menu.main]]
    name = "Music"
    url = "/garden/"
    weight = 1
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.main]]
    name = "Sound Installations"
    url = "/library/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4


[taxonomies]
  music_tags = 'music_tags'
  project_tags = 'project_tags'
  artwork_tags = 'artwork_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'